### PR TITLE
Add unlink command (fix #9)

### LINKED ISSUE #9: Use unlink on symbolic links inside builddir before removing old build
rmtree seems to try to follow symlic and tries to remove eg. files/ resulting either data loss or build error with "operation not permitted.'

### PR DESCRIPTION
**Pull request by tharna**
Runs it when removing old builddir.

### CODE REVIEW

**Comment by tharna** [comment]
@tcmug how does this look to you?

**Comment by tcmug** [comment]
Yes - perfect -- I trust it works?

**Comment by tharna** [comment]
Fixed one small indentation mistake and changed to non-destructive iteration of link settings. So now it should work.

**Comment by tcmug** [comment]
Yiss! :)

**Pull request merged**
